Some more updates, still working on zip creation

diff --git a/tools/toolbox b/tools/toolbox
--- a/tools/toolbox
+++ b/tools/toolbox
@@ -128,19 +128,39 @@ function cleanPlayGround ()
 
 function pullSystemFromPhone ()
 {
+    
     [ -d $BASEDIR/source ] || mkdir $BASEDIR/source
     adb shell mkdir /mnt/sdcard/tmpModStudio/;
-    for i in `adb shell su -c find /system -iname "*.apk" -o -iname "*.jar" -o -iname "*.odex"`;do
-        realOut=$(echo $i | sed "s#\s##g")
-        echo "Grabbing $realOut";
-        thefile=$(echo $realOut | awk -F\/ '{print $NF}');
-        echo "adb shell su -c cp $realOut /mnt/sdcard/tmpModStudio/$thefile";
-        adb shell su -c cp $realOut /mnt/sdcard/tmpModStudio/$thefile;
-        thepath=$(echo $realOut | awk -F\/ 'sub(FS $NF,x)');
-        mkdir -p $BASEDIR/source/$thepath
-        adb pull /mnt/sdcard/tmpModStudio/$thefile $BASEDIR/source/$thepath/
-        adb shell rm /mnt/sdcard/tmpModStudio/$thefile
-    done;
+    
+    if [ "$1" == 'all' ]; then
+      for i in `adb shell su -c find /system -type f`;do
+          realOut=$(echo $i | sed "s#\s##g")
+          echo "Grabbing $realOut";
+          thefile=$(echo $realOut | awk -F\/ '{print $NF}');
+          echo "adb shell su -c cp $realOut /mnt/sdcard/tmpModStudio/$thefile";
+          adb shell su -c cp $realOut /mnt/sdcard/tmpModStudio/$thefile;
+          thepath=$(echo $realOut | awk -F\/ 'sub(FS $NF,x)');
+          mkdir -p $BASEDIR/source/$thepath
+          echo "adb pull /mnt/sdcard/tmpModStudio/$thefile $BASEDIR/source/$thepath/"
+          adb pull /mnt/sdcard/tmpModStudio/$thefile $BASEDIR/source/$thepath/
+          adb shell rm /mnt/sdcard/tmpModStudio/$thefile
+      done;
+    else
+      for i in `adb shell su -c find /system -iname "*.apk" -o -iname "*.jar" -o -iname "*.odex"`;do
+          realOut=$(echo $i | sed "s#\s##g")
+          echo "Grabbing $realOut";
+          thefile=$(echo $realOut | awk -F\/ '{print $NF}');
+          echo "adb shell su -c cp $realOut /mnt/sdcard/tmpModStudio/$thefile";
+          adb shell su -c cp $realOut /mnt/sdcard/tmpModStudio/$thefile;
+          thepath=$(echo $realOut | awk -F\/ 'sub(FS $NF,x)');
+          mkdir -p $BASEDIR/source/$thepath
+          echo "adb pull /mnt/sdcard/tmpModStudio/$thefile $BASEDIR/source/$thepath/"
+          adb pull /mnt/sdcard/tmpModStudio/$thefile $BASEDIR/source/$thepath/
+          adb shell rm /mnt/sdcard/tmpModStudio/$thefile
+      done;
+    fi;
+      
+      
     adb shell rm -rf /mnt/sdcard/tmpModStudio
     #rm -rf $BASEDIR/sourceTest
 }
@@ -158,14 +178,67 @@ function pullSystemFromROM ()
     echo "Unzipping ROM, this may take a few minutes."
     unzip $tempROM 
     echo "Done, creating file list now."
-    for i in `find $BASEDIR/working/system/ -iname "*.apk" -o -iname "*.jar" -o -iname "*.odex"`;do
-        thefile=$(echo $i | awk -F\/ '{print $NF}');
-        thepath=$(echo $i | awk -F\/ 'sub(FS $NF,x)' | sed "s#$BASEDIR/working/##g");
-        mkdir -p $BASEDIR/source/$thepath
-        echo "cp $i $BASEDIR/source/$thepath/"
-        cp "$i" $BASEDIR/source/$thepath/
-    done;
+    if [ "$2" == 'all' ];then
+      for i in `find $BASEDIR/working/system/ -type f`;do
+          thefile=$(echo $i | awk -F\/ '{print $NF}');
+          thepath=$(echo $i | awk -F\/ 'sub(FS $NF,x)' | sed "s#$BASEDIR/working/##g");
+          mkdir -p $BASEDIR/source/$thepath
+          echo "cp $i $BASEDIR/source/$thepath/"
+          cp "$i" $BASEDIR/source/$thepath/
+      done;
+    else
+      for i in `find $BASEDIR/working/system/ -iname "*.apk" -o -iname "*.jar" -o -iname "*.odex"`;do
+          thefile=$(echo $i | awk -F\/ '{print $NF}');
+          thepath=$(echo $i | awk -F\/ 'sub(FS $NF,x)' | sed "s#$BASEDIR/working/##g");
+          mkdir -p $BASEDIR/source/$thepath
+          echo "cp $i $BASEDIR/source/$thepath/"
+          cp "$i" $BASEDIR/source/$thepath/
+      done;
+    fi;
     cd $cwd
+    rm -rf $BASEDIR/working
+}
+
+function pullSystemFromIMG ()
+{
+    IMG=$1
+    cwd=`pwd`
+    [ -d $BASEDIR/source ] || mkdir $BASEDIR/source
+    [ -f $IMG ] || (echo "Can't locate the IMG file specified" && return 1)
+    [ -d $BASEDIR/working ] || mkdir $BASEDIR/working
+    echo "Making working copy of IMG and figuring out IMG type, this may take a few minutes."
+    cp $IMG $BASEDIR/working/
+    cd $BASEDIR/working/
+    tempIMG=$(find . -iname "*.img*")
+    
+    [ -d $BASEDIR/working/mount ] || mkdir $BASEDIR/working/mount
+    echo "Need sudo to mount the image"
+    sudo mount -o loop $tempIMG $BASEDIR/working/mount
+    if [ $? -ne 0 ]; then
+      $BASEDIR/tools/ext4_utils_r4.3/simg2img $tempIMG $tempIMG.raw
+      sudo mount -o loop $tempIMG.raw $BASEDIR/working/mount
+      if [ $? -ne 0 ]; then
+        echo "Cannot work with the provided IMG"
+        return 1
+      fi
+    fi
+    mkdir -p $BASEDIR/source/system/
+    if [ "$2" == 'all' ];then
+      
+      cp -arvf $BASEDIR/working/mount/* $BASEDIR/source/system/
+    else
+      echo "Done, creating file list now."
+      for i in `find $BASEDIR/working/mount/ -iname "*.apk" -o -iname "*.jar" -o -iname "*.odex"`;do
+          thefile=$(echo $i | awk -F\/ '{print $NF}');
+          thepath=$(echo $i | awk -F\/ 'sub(FS $NF,x)' | sed "s#$BASEDIR/working/mount/##g");
+          echo "mkdir -p $BASEDIR/source/system/$thepath"
+          mkdir -p $BASEDIR/source/system/$thepath
+          echo "cp $i $BASEDIR/source/system/$thepath/"
+          cp "$i" $BASEDIR/source/system/$thepath/
+      done;
+    fi
+    cd $cwd
+    sudo umount $BASEDIR/working/mount
     rm -rf $BASEDIR/working
 }
 
@@ -185,6 +258,44 @@ function buildMod ()
 function buildFlashable ()
 {
   echo "Feature coming soon"
+  dirs=$(find $BASEDIR/playground -type d)
+
+  #copy everything to working dir
+  
+  #insert dexopt-wrapper if self odexing
+  
+  
+#cat <<EOF > /etc/Advance-info/firstboot.sh
+  cat << EOF
+ui_print("*********************************************");  
+ui_print("This flashable zip made possible by modStudio");  
+ui_print("*********************************************");  
+
+unmount("/system"); 
+ui_print("Mounting System"); 
+run_program("/sbin/mount", "-t", "auto", "/system"); 
+
+unmount("/data"); 
+ui_print("Mounting Data"); 
+run_program("/sbin/mount", "-t", "auto", "/data");
+
+ui_print("Extracting all the systems"); 
+package_extract_dir("system", "/system"); 
+
+ui_print("Setting permissions on sqlite3"); 
+set_perm(0, 0, 0777, "/system/xbin/sqlite3"); 
+
+ui_print("Executing unlockHotspot"); 
+package_extract_file("tmp/unlockHotspot", "/data/local/tmp/unlockHotspot.sh"); 
+set_perm(0, 0, 0777, "/data/local//tmp/unlockHotspot.sh");  
+run_program("/data/local//tmp/unlockHotspot.sh"); 
+
+ 
+ui_print("******************************************"); 
+ui_print("        Successfully Installed"); 
+ui_print("******************************************"); 
+set_progress(1.0); 
+EOF
 }
 
 function odex ()
